const quickSandFont = 'Quicksand';
const categoriesUrl = 'https://opentdb.com/api_category.php';
const quizBaseUrl = 'https://opentdb.com/api.php?';
const amountString = 'amount=';
const categoryString = '&category=';
const difficultyString = '&difficulty=';
const typeString = '&type=';
const categoriesKey = 'trivia_categories';
const id = 'id';
const name = 'name';
const appBarInstruction = 'Swipe below to select quiz category.';
const fetchingData = 'Fetching Categories...';
const selectQuizType = 'Select Quize Type.';
const quizTypeInstruction = 'Tap to select the type subcategory of your choice quiz.';
const multipleChoice = 'Multiple Choice Questions.';
const trueOrFalse = 'True Or False Questions.';
const anyQuestion = 'Combination Of Both.';
const hard = 'Hard.';
const medium = 'Medium.';
const easy = 'Easy.';
const anyDifficulty = 'Any Difficulty.';
const quizDifficultyInstruction = 'Tap to select the difficulty subcategory of your choice quiz.';
const selectQuizDifficulty = 'Select Quiz Difficulty.';
const ten = 'Ten.';
const twenty = 'Twenty.';
const thirty = 'Thirty.';
const fourty = 'Fourty.';
const fifty = 'Fifty.';
const quizeNumberInstruction = 'Tap to select how many quiz questions you want to answer.';
const selectQuizNumber = 'Select Number of Quizes.';
const startQuiz = 'Start Quiz';
const youSelected = 'You selected ';
const tapToDeselect = ' Tap to deselect.';
const emptyString = '';
const multipleString = 'multiple';
const boolString = 'boolean';
const questionString = 'question';
const correctAnswerString = 'correct_answer';
const incorrectAnswersString = 'incorrect_answers';
const resultsKey = 'results';