
const quotesUrl = 'https://api.api-ninjas.com/v1/quotes?category=inspirational';
const backgroundImageUrl = 'https://api.api-ninjas.com/v1/randomimage?category=city';
const apiKey = 'X-Api-Key';
const apiKeyValue = 'OfTZSV398E46GhtXUT6svQ==vhX1U1xMpAm7bspP';
const acceptKey = 'Accept';
const acceptKeyValue = 'image/jpg';
const imageFilePath = 'assets/FB_IMG_1691828515571.png';
const quickSandFont = 'Quicksand';
const loadingString = 'Loading New Quote...';
const noQuotes = 'Unable to fetch quotes!😢. Please check your internet connection...';
const quotesKey = 'quote';
const lengthOfQuotes = 'quotesLength';
const saveQuoteTitle = 'Save Quote';
const saveQuoteContent = 'Proceed to save this quote?';
const cancel = 'Cancel';
const saveQuoteKey = 'SaveQuote';
const shareQuoteKey = 'ShareQuote';
const saving = 'Saving...';
const saved = 'Saved🎉';