
const quotesUrl = 'https://api.api-ninjas.com/v1/quotes?category=inspirational';
const backgroundImageUrl = 'https://api.api-ninjas.com/v1/randomimage?category=city';
const apiKey = 'X-Api-Key';
const apiKeyValue = 'OfTZSV398E46GhtXUT6svQ==vhX1U1xMpAm7bspP';
const acceptKey = 'Accept';
const acceptKeyValue = 'image/jpg';
const imageFilePath = 'assets/FB_IMG_1691828515571.png';
const quickSandFont = 'Quicksand';
const loadingString = 'Loading New Quote...';
const noQuotes = 'Unable to fetch quotes!😢. Please check your internet connection...';
const quotesKey = 'quote';
const authorKey = 'author';
const deleteQuote = 'Delete Quote? 🗑️';
const confirmDeleteQuote = 'Are you sure you want to delete this quote?';
const lengthOfQuotes = 'quotesLength';
const saveQuoteTitle = 'Save Quote';
const shareQuote = 'Share Quote';
const refreshQuote = 'Refresh';
const viewFavorites = 'View Favorites';
const favoriteQuotes = 'Your Favorite Quotes.';
const quoteDeleted = 'Quote Deleted! 🗑️';
const saveQuoteContent = 'Proceed to add this quote to your Favorites?';
const cancel = 'Cancel';
const saveQuoteKey = 'Add';
const shareQuoteKey = 'ShareQuote';
const deleteQuoteKey = 'DeleteQuote';
const saving = 'Saving...';
const saved = 'Quote Saved🎉';
const quoteExists = 'Quote Already Saved!';
const noSavedQuotes = 'Oops! You currently have no saved quotes to display...';
const tempQuoteString = 'temporaryQuote';
const noQuoteToSave = 'No Quote To Save';
const emptyString = '';
const dashString = '  -- ';